# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'pim/akonadi' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/mailcommon' : '@same'
    'pim/pimcommon' : '@same'
    'pim/akonadi-notes' : '@same'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/kcalendarcore' : '@latest-kf6'
    'pim/akonadi' : '@latest-kf6'
    'pim/kidentitymanagement' : '@latest-kf6'
    'pim/kmailtransport' : '@latest-kf6'
    'pim/kmime' : '@latest-kf6'
    'pim/kpimtextedit' : '@latest-kf6'
    'pim/mailcommon' : '@latest-kf6'
    'pim/pimcommon' : '@latest-kf6'
    'pim/akonadi-notes' : '@latest-kf6'
