# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/libkdepim' : '@same'
    'kde/pim/mailcommon' : '@same'
    'kde/pim/pimcommon' : '@same'
    'kde/pim/akonadi-notes' : '@same'
