# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcalendarcore': '@latest-kf6'
    'frameworks/kstatusnotifieritem': '@latest-kf6'
    'frameworks/kuserfeedback': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'pim/akonadi': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kmailtransport': '@same'
    'pim/kmime': '@same'
    'pim/mailcommon': '@same'
    'pim/pimcommon': '@same'
    'libraries/ktextaddons': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kdbusaddons': '@latest-kf6'

Options:
 require-passing-tests-on: ['@all']
